case node['platform']
when 'centos'
  default['mongodb']['default_init'] = '/lib/systemd/system/mongod.service'
  default['mongodb']['init_path'] = '/etc/init.d'
  default['mongodb']['package_name'] = 'mongodb-org'
  default['mongodb']['config_path'] = '/etc/mongod'
  default['mongodb']['pid_path'] = '/var/run/mongodb'
  default['mongodb']['bin_path'] = '/usr/bin/mongod'
  default['mongodb']['log_path'] = '/var/log/mongodb'
  default['mongodb']['db_path'] = '/var/lib/mongo'
  default['mongodb']['user'] = 'mongod'
  default['mongodb']['group'] = 'mongod'
  default['mongodb']['bind_address'] = '127.0.0.1'
  default['mongodb']['port'] = '27017'
when 'ubuntu'
  default['mongodb']['default_init'] = '/etc/init.d/mongodb'
  default['mongodb']['init_path'] = '/etc/init.d'
  default['mongodb']['package_name'] = 'mongodb'
  default['mongodb']['config_path'] = '/etc/mongod'
  default['mongodb']['pid_path'] = '/var/run/mongodb'
  default['mongodb']['bin_path'] = '/usr/bin/mongod'
  default['mongodb']['log_path'] = '/var/log/mongodb'
  default['mongodb']['db_path'] = '/var/lib/mongo'
  default['mongodb']['user'] = 'mongodb'
  default['mongodb']['group'] = 'mongodb'
  default['mongodb']['bind_address'] = '127.0.0.1'
  default['mongodb']['port'] = '27017'
end

default['mongodb']['instances'] = {}
